### PR TITLE
feat: logger

### LINKED ISSUE #9: Using `serializable.serializable_class` during import configures root logger
# Description
If some user of py-serializable calls [`serializable.serializable_class`](https://github.com/madpah/serializable/blob/9bc4abccc9cabed5f9808101a8d25717b86f01b4/serializable/__init__.py#L1086) before configuring the root logger (which is common during import blocks), the root logger ends up configured with the default basic configuration.

This happens because we call [`logging.debug` in `ObjectMetadataLibrary.register_klass`](https://github.com/madpah/serializable/blob/9bc4abccc9cabed5f9808101a8d25717b86f01b4/serializable/__init__.py#L969). Calling `logging.debug` (or similar) will [automatically call `logging.basicConfig`](https://docs.python.org/3/library/logging.html#logging.basicConfig) if no handlers are configured for the root logger.

We should probably do what most modules do and set up our own logger and `NullHandler` rather than using the root logger.

# Example
```python
import logging
import serializable

@serializable.serializable_class
class Foo:
    pass

_logger = logging.getLogger()
_logger.addHandler(logging.NullHandler())
_logger.error("foo")
```
Outputs `ERROR:root:foo`, which shouldn't happen if I only configure a `NullHandler`.

# Workaround
I'm currently working around this by wrapping the import of anything that uses `py-serializable` (in this case, CycloneDX) in a logging configuration hack:
```python
_root_logger = logging.getLogger()
_root_null_handler = logging.NullHandler()
_root_logger.addHandler(_root_null_handler)
from cyclonedx.model.bom import Bom
_root_logger.removeHandler(_root_null_handler)
```

# Version Info
- Python 3.10.9 & Python 3.9.13
- py-serializable 0.11.1

### PR DESCRIPTION
**Pull request by jkowalleck**
Fixes #9.
Supersedes #10

### CODE REVIEW

**Comment by jkowalleck** [comment]
#10 plus some rollbacks and revisions.
Incorporated notes from @kroeschl - https://github.com/madpah/serializable/pull/10#issuecomment-1737600784

changes since #10
- used the existing variable `logger` - as it was already public API
- used the existing logger name `serializable`

**Review by madpah — APPROVED** [review]

**Comment by jkowalleck** [comment]
@kroeschl could I ask you for some feedback?

**Comment by kroeschl** [comment]
> @kroeschl could I ask you for some feedback?

Tested and verified that this does fix #9, and the diff looks good to me.

**Comment by jkowalleck** [comment]
feature was made available in v1.17

**Pull request merged**
